apiVersion: v1
kind: Secret
metadata:
  name: {{ name }}-secret
  namespace: {{ namespace }}
  labels:
    app: postgres
    instance: {{ name }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ password }}"
