apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app: postgres
    instance: {{ name }}
    image-type: {{ image_type }}
spec:
  replicas: 1
  serviceName: {{ name }}
  selector:
    matchLabels:
      app: postgres
      instance: {{ name }}
  template:
    metadata:
      labels:
        app: postgres
        instance: {{ name }}
        image-type: {{ image_type }}
    spec:
      {% if image_type == "pg_durable" %}
      imagePullSecrets:
      - name: acr-secret
      {% endif %}
      containers:
      - name: postgres
        image: {{ image }}
        ports:
        - containerPort: 5432
          name: postgres
        args:
          - "-c"
          - "wal_level=replica"
          - "-c"
          - "max_wal_senders=3"
          - "-c"
          - "hba_file=/etc/postgresql/pg_hba.conf"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ name }}-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        {% if image_type == "pg_durable" %}
        - name: PGDATABASE
          value: postgres
        {% endif %}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql
          readOnly: true
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ name }}-pvc
      - name: postgres-config
        configMap:
          name: {{ name }}-config

